blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.homePage, name='home'),
    path('tag/<slug:tag_slug>/', views.homePage, name='products_by_tag'),  # Added trailing slash
    path('product/<int:pk>/<slug:slug>/', views.productDetail, name='product_detail'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update-item/', views.updateItem, name='update_item'),
    path('register/', views.registerPage.as_view(), name='register'),
    path('login/', views.loginPage.as_view(), name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('account/', views.accountPage, name='account'),
    path('search/', views.post_search, name='search'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-error/', views.payment_error, name='payment_error'),
   
    
    # Added payment error route
    # path('payment-callback/', views.payment_callback, name='payment_callback'),  # Added payment callback route
]

onlineShop/urls.py
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

from taggit.managers import TaggableManager

from django.core.validators import MinValueValidator, MaxValueValidator


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.title}{ext}"
    return f"products/{instance.author}/{final_name}"


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField()


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to='media/', blank=True, default='man.png')
    email = models.EmailField(max_length=200, null=True)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=500, blank=True, null=True)
    ip_address = models.OneToOneField(IPAddress, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=20)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField()
    active = models.BooleanField()

    def __str__(self):
        return self.code


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_orderd = models.DateTimeField(auto_now_add=True)
    coplete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True, blank=True)
    coupons = models.ForeignKey(Coupon, on_delete=models.SET_NULL, blank=True, null=True)

    @property
    def get_total_products(self):
        orderItems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderItems])
        return total

    @property
    def get_total_price(self):
        orderItems = self.orderitem_set.all()
        total = sum([item.get_total_price for item in orderItems])
        return total


    @property
    def get_last_total_price(self):
        total = self.get_total_price
        if self.coupons:
            total -= self.coupons.discount

        if total < 0:
            total = 0
        return total


class Delivery(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField()
    active = models.BooleanField()



class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    address = models.TextField(max_length=500)
    city = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)


class Product(models.Model):
    STATUS_CHOICES = (
        ('published', 'Published'),
        ('draft', 'Draft'),
    )
    title = models.CharField(max_length=80)
    slug = models.CharField(max_length=100)
    price = models.FloatField()
    offPrice = models.FloatField(null=True, blank=True)
    description = models.TextField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    image = models.ImageField(null=True, blank=True)
    status = models.CharField(default='published', max_length=20, choices=STATUS_CHOICES)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    ratings = GenericRelation(Rating, related_query_name='products')
    hits = models.ManyToManyField(IPAddress, blank=True, related_name='hits')
    tags = TaggableManager()

    # published = ProductPublishManager()
    # objects = PostManager()

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        url = reverse('blog:product_detail', args=[self.id, self.slug])
        return url


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total_price(self):
        if self.product.offPrice:
            price = self.quantity * self.product.offPrice
        else:
            price = self.quantity * self.product.price
        return price

blog/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class AccountForm(forms.Form):
    first_name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100, required=False)
    email = forms.EmailField(max_length=100, required=False)
    phone = forms.CharField(max_length=12, required=False)
    address = forms.CharField(max_length=500, required=False)
    image = forms.FileField(required=False)

blog/views.py
from django.contrib import messages

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
import json

from django.urls import reverse_lazy

from .models import *

from .forms import CreateUserForm, AccountForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import FormView
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth import logout

from django.db.models import Q

from django.db.models import Count


import random

from taggit.models import Tag

from django.contrib.auth.decorators import login_required






def homePage(request, tag_slug=None):
    products = Product.objects.filter(status='published')
    tag =None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = Product.objects.filter(tags__in=[tag])

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, coplete=False)

        order_items_count = order.get_total_products

    else:
        order_items_count = 0


    # Paginate Site With 6 Items Per A Page
    paginator = Paginator(products, 8)
    page = request.GET.get('page')

    # Post Of Certain Page
    try:
        products = paginator.page(page)

    # If Page Not Integer
    except PageNotAnInteger:
        products = paginator.page(1)

    # If Page NOt Exists
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {
        'products': products,
        'page': page,
        'order_items_count':  order_items_count,
    }
    return render(request, 'blog/partials/content.html', context)


def productDetail(request, pk, slug):
    product = get_object_or_404(Product, id=pk, slug=slug, status='published')

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, coplete=False)
        order_items_count = order.get_total_products

        user_ip = request.user.customer.ip_address
        if user_ip not in product.hits.all():
            product.hits.add(user_ip)
    else:
        order_items_count = 0

    product_tags = product.tags.values_list('id', flat=True)
    similar_products = Product.objects.filter(tags__in=product_tags, status='published').exclude(id=product.id)
    # print(similar_products)
    similar_products = similar_products.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    context = {
        'product': product,
        'similar_products': similar_products,
        'order_items_count': order_items_count,

    }
    return render(request, 'blog/partials/product_detail.html', context)
def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, coplete=False)
        items = OrderItem.objects.filter(order=order)
        delivery = Delivery.objects.filter(active=True)

        # Product Charges (static for now or can be dynamic)
        product_charges = 100  # Example static charge
        total_price = order.get_total_price  # No parentheses here as it's a property
        total_price_with_charges = total_price + product_charges

        # Default shipping fee (3000)
        shipping_fee = 3000

        if request.method == "POST":
            now = timezone.now()
            code = request.POST['code']
            
            # Coupon logic removed as requested

        order_items_count = order.get_total_products

        context = {
            'items': items,
            'order': order,
            'order_items_count': order_items_count,
            'delivery': delivery,
            'product_charges': product_charges,
            'total_price_with_charges': total_price_with_charges,  # Add this to pass the new total
            'shipping_fee': shipping_fee  # Pass the default shipping fee to the template
        }

        return render(request, 'blog/partials/cart.html', context)


# views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Order, OrderItem

def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, coplete=False)
        items = OrderItem.objects.filter(order=order)

        # Check if customer has filled in all necessary information
        if not (customer.first_name and customer.last_name and customer.address and customer.email and customer.phone):
            messages.error(request, 'Complete your personal information')
            return redirect('blog:cart')

    else:
        items = []
        order = {
            'get_total_price': 0,
            'get_total_products': 0,
        }
        return redirect('blog:login')

    # Adding shipping fee
    shipping_fee = 2  # Example shipping fee

    # Calculate total price including shipping fee
    total_price = order.get_total_price + shipping_fee
    
    if not order:
        # Handle case when order is not available
        return redirect('blog:cart')
    
    # Use order details and customer info for payment
    order_total = order.get_last_total_price
    customer_email = customer.email
    customer_phone = customer.phone
    customer_address = customer.address
    customer_name = f"{customer.first_name} {customer.last_name}"
    
    products_list = ', '.join([f"{item.product.title} x {item.quantity}" for item in items])
    
    
    
    context = {
        'items': items,
        'order': order,
        'customer': customer,
        'shipping_fee': shipping_fee,
        'total_price': total_price,
        'order_total': order_total,
        'customer_email': customer_email,
        'customer_name': customer_name,
        'products_list': products_list,
        'customer_phone': customer_phone,
        'customer_address': customer_address,
        'tx_ref': f"txref-{random.randint(100000, 999999)}",
    }

    return render(request, 'blog/partials/checkout.html', context)
print("items")


# @login_required
# def payment(request):
#     customer = request.user.customer
#     order, created = Order.objects.get_or_create(customer=customer, coplete=False)

    
    # if not order:
    #     # Handle case when order is not available
    #     return redirect('blog:cart')
    
    # # Use order details and customer info for payment
    # order_total = order.get_last_total_price
    # customer_email = customer.email
    # customer_phone = customer.phone
    # customer_address = customer.address
    # customer_name = f"{customer.first_name} {customer.last_name}"

#     context = {
        # 'order_total': order_total,
        # 'customer_email': customer_email,
        # 'customer_name': customer_name,
        # 'customer_phone': customer_phone,
        # 'customer_address': customer_address,
        # 'tx_ref': f"txref-{random.randint(100000, 999999)}",  # Generate a unique reference for the transaction
#     }
    
#     return render(request, 'blog/partials/payment.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=request.user.customer, coplete=False)
    orderItem, created = OrderItem.objects.get_or_create(product=product, order=order)


    if action == "add":
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == "remove":
        orderItem.quantity = (orderItem.quantity - 1)
    elif action == "delete":
        orderItem.delete()

    orderItem.save()
    if action == "delete":
        orderItem.delete()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('update item', safe=False)


class registerPage(FormView):
    template_name = 'blog/account/register.html'
    form_class = CreateUserForm
    success_url = reverse_lazy('blog:login')

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('blog:home')
        return super().get(*args, **kwargs)


    def form_valid(self, form):
        user = form.save()
        email = form.cleaned_data['email']
        customer = Customer.objects.create(user=user, email=email)
        return super().form_valid(form)


class loginPage(LoginView):
    template_name = 'blog/account/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('blog:home')

    def form_invalid(self, form):
        messages.error(self.request, 'Username or password is Incorrect')
        return super().form_invalid(self)


@login_required
def logoutPage(request):
    logout(request)
    return redirect('blog:login')


@login_required
def accountPage(request):
    customer = request.user.customer
    order_history = Order.objects.filter(customer=customer, coplete=True)
    if request.method == "POST":
        accForm = AccountForm(data=request.POST)
        if accForm.is_valid():
            accForm = AccountForm(data=request.POST)
            if accForm.is_valid():
                cd = accForm.cleaned_data
                customer.first_name = cd['first_name']
                customer.last_name = cd['last_name']
                customer.email = cd['email']
                customer.phone = cd['phone']
                customer.address = cd['address']
                image = request.FILES.get('image')
                if image:
                    customer.image = image
                customer.save()
                return redirect('blog:account')
    else:
        accForm = AccountForm()
    context = {
        'customer': customer,
        'accForm': accForm,

blog/templates/blog/partials/cart.html
{% extends 'blog/parents/base.html' %}

{% block title %}Cart{% endblock %}

{% block head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <style>
        a {
            text-decoration: none;
        }

        .title {
            margin-bottom: 5vh
        }

        .card {
            margin: auto;
            max-width: 950px;
            width: 90%;
            box-shadow: 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 1rem;
            border: transparent
        }

        @media (max-width: 767px) {
            .card {
                margin: 3vh auto
            }
        }

        .cart {
            background-color: #fff;
            padding: 4vh 5vh;
            border-bottom-left-radius: 1rem;
            border-top-left-radius: 1rem
        }

        @media (max-width: 767px) {
            .cart {
                padding: 4vh;
                border-bottom-left-radius: unset;
                border-top-right-radius: 1rem
            }
        }

        .summary {
            background-color: #ddd;
            border-top-right-radius: 1rem;
            border-bottom-right-radius: 1rem;
            padding: 4vh;
            color: rgb(65, 65, 65)
        }

        @media (max-width: 767px) {
            .summary {
                border-top-right-radius: unset;
                border-bottom-left-radius: 1rem
            }
        }

        .summary .col-2 {
            padding: 0
        }

        .summary .col-10 {
            padding: 0
        }

        .row {
            margin: 0
        }

        .title b {
            font-size: 1.5rem
        }

        .main {
            margin: 0;
            padding: 2vh 0;
            width: 100%
        }

        .col-2,
        .col {
            padding: 0 1vh
        }

        a {
            padding: 0 1vh
        }

        .close {
            margin-left: auto;
            font-size: 0.7rem
        }

        img {
            width: 3.5rem
        }

        .back-to-shop {
            margin-top: 4.5rem
        }

        h5 {
            margin-top: 4vh
        }

        hr {
            margin-top: 1.25rem
        }

        form {
            padding: 2vh 0
        }

        select {
            border: 1px solid rgba(0, 0, 0, 0.137);
            padding: 1.5vh 1vh;
            margin-bottom: 4vh;
            outline: none;
            width: 100%;
            background-color: rgb(247, 247, 247)
        }

        input {
            border: 1px solid rgba(0, 0, 0, 0.137);
            padding: 1vh;
            margin-bottom: 4vh;
            outline: none;
            width: 100%;
            background-color: rgb(247, 247, 247)
        }

        input:focus::-webkit-input-placeholder {
            color: transparent
        }

        #btn {
            background-color: #000;
            border-color: #000;
            color: white;
            width: 100%;
            font-size: 0.7rem;
            margin-top: 4vh;
            padding: 1vh;
            border-radius: 0
        }

        #btn:focus {
            box-shadow: none;
            outline: none;
            box-shadow: none;
            color: white;
            -webkit-box-shadow: none;
            -webkit-user-select: none;
            transition: none
        }

        #btn:hover {
            color: white
        }

        a {
            color: black
        }

        a:hover {
            color: black;
            text-decoration: none
        }

        #code {
            background-image: linear-gradient(to left, rgba(255, 255, 255, 0.253), rgba(255, 255, 255, 0.185)), url("https://img.icons8.com/small/16/000000/long-arrow-right.png");
            background-repeat: no-repeat;
            background-position-x: 95%;
            background-position-y: center
        }
    </style>
{% endblock %}


{% block content %}
    <div class="card my-5">
        <div class="row">
            <div class="col-md-8 cart">
                <div class="title">
                    <div class="row">
                        <div class="col">
                            <h4><b>Shopping Cart</b></h4>
                        </div>
                        <div class="col align-self-center text-right text-muted">{{ order.get_total_products }} items
                        </div>
                    </div>
                </div>
                {% for item in items %}
                    <div class="row">
                        <div class="row main align-items-center">
                            <div class="col-2"><a href="{{ item.product.get_absolute_url }}"><img class="img-fluid"
                                                                                                  src="{{ item.product.image.url }}"></a>
                            </div>
                            <div class="col">
                                <div class="row text-muted">{{ item.product.title }}</div>
                                <div class="row">{{ item.product.description|truncatechars:15 }}</div>
                            </div>

                            <div class="col text-decoration-none"><a class="update-item h5" href=""
                                                                     data-product="{{ item.product.id }}"
                                                                     data-action="remove">-</a><a
                                    class="border">{{ item.quantity }}</a><a href="" class="update-item h5"
                                                                             data-product="{{ item.product.id }}"
                                                                             data-action="add">+</a></div>
                            <div class="col">$ {{ item.get_total_price|floatformat:2 }}<a
                                    class="update-item close mx-4 h5" href="" data-product="{{ item.product.id }}"
                                    data-action="delete">&#10005;</a></div>
                        </div>
                    </div>
                {% endfor %}
                <a href="{% url 'blog:home' %}">
                    <div class="back-to-shop">&leftarrow;<span class="text-muted">Back to shop</span></div>
                </a>
            </div>
            <div class="col-md-4 summary">
                <div>
                    <h5><b>Summary</b></h5>
                </div>
                <hr>
                <div class="row">
                    <div class="col" style="padding-left:0;">{{ order.get_total_products }} ITEMS</div>
                    <div class="col text-right">$ {{ order.get_total_price|floatformat:2 }}</div>
                </div>
                <form method="POST">
                    <p>SHIPPING</p>
                    <select name="delivery">
                        {% for item in delivery %}
                            <option class="text-muted">{{ item.name }}- ₦{{ item.price }}</option>
                        {% endfor %}
                    </select>
                    <p>GIVE CODE</p> <input type="text" id="code" placeholder="Enter your code" name="code">
                    {% if messages %}
                        {% for msg in messages %}
                            {% if msg.tags == 'info' %}
                                <small class="text-danger">{{ msg }}</small>

                            {% endif %}
                        {% endfor %}
                    {% endif %}

                {% if order.coupons %}<h7 class="text-success">discount: -₦{{ order.coupons.discount }}</h7>{% endif %}

                    <button type="submit" class="btn btn-block btn-info">CHECK</button>
                    {% csrf_token %}
                </form>
                <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                    <div class="col">TOTAL PRICE</div>
                    <div class="col text-right">₦ {{ order.get_last_total_price|floatformat:2 }}</div>
                </div>
                <a href="{% if order_items_count == 0 %}{% url 'blog:cart' %} {% else %}{% url 'blog:checkout' %}{% endif %}">
                    <button id="btn">CHECKOUT</button>
                </a>
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger my-3" role="alert"
                                 style="position: absolute; margin-left: -20px; width: 300px">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/partials/content.html
{% extends 'blog/parents/base.html' %}
{% load blog_tags %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
    {% include 'blog/partials/header.html' %}

    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            {% if product.offPrice %}
                                <!-- Sale badge-->
                                <div class="badge bg-dark text-white position-absolute" 
                                     style="top: 0.5rem; right: 0.5rem">
                                    Sale
                                </div>
                            {% endif %}
                            <!-- Product image-->
                            <a href="{{ product.get_absolute_url }}">
                                <img class="card-img-top img-fluid" 
                                     src="{{ product.image.url }}" 
                                     alt="..."/>
                            </a>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.title }}</h5>
                                    <!-- Product price-->
                                    {% if product.offPrice %}
                                        <span class="text-muted text-decoration-line-through">
                                            ₦{{ product.price }}
                                        </span>
                                        ₦{{ product.offPrice }}
                                    {% else %}
                                    ₦{{ product.price }}
                                    {% endif %}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="d-flex flex-column gap-2">
                                    <!-- View options button -->
                                    <a class="btn btn-outline-dark" 
                                       href="{{ product.get_absolute_url }}">
                                        View options
                                    </a>

                                    <!-- Add Cart button -->
                                    <a class="btn btn-outline-info update-item" 
                                       data-product="{{ product.id }}" 
                                       data-action="add" 
                                       {% if not request.user.authentication %}href="{% url 'blog:login' %}"{% endif %}>
                                        Add Cart
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

    {% include 'blog/partials/pagination.html' with page=products %}
    {% show_top_products %}
    <hr style="color: #F8F9FA">
    {% show_most_viewed_products %}
{% endblock %}

blog/templates/blog/partials/footer.html
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p>
    </div>

</footer>

blog/templates/blog/partials/header.html
<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Shop in style</h1>

            <!-- Responsive Search Bar -->
            <div class="d-flex justify-content-center mt-4">
                <form method="get" action="{% url 'blog:search' %}" class="w-100" style="max-width: 400px;">
                    <div class="input-group">
                        <input 
                            id="search-input" 
                            type="search" 
                            class="form-control" 
                            placeholder="Search..." 
                            name="query" 
                            value="{{ request.GET.query }}" 
                        />
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</header>

blog/templates/blog/partials/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Payment</title>
</head>
<body>
<div class="col-md-12 text-center my-4">
    <a href="{% url 'blog:cart' %}"><button type="button" class="btn btn-outline-danger">Cancel</button></a>
    <a href="{% url 'blog:payment_success' %}"><button type="button" class="btn btn-outline-success">Pay</button></a>
</div>
</body>
</html>