blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.homePage, name='home'),
    path('tag/<slug:tag_slug>/', views.homePage, name='products_by_tag'),  # Added trailing slash
    path('product/<int:pk>/<slug:slug>/', views.productDetail, name='product_detail'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update-item/', views.updateItem, name='update_item'),
    path('register/', views.registerPage.as_view(), name='register'),
    path('login/', views.loginPage.as_view(), name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('account/', views.accountPage, name='account'),
    path('search/', views.post_search, name='search'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-error/', views.payment_error, name='payment_error'),
   
    
    # Added payment error route
    # path('payment-callback/', views.payment_callback, name='payment_callback'),  # Added payment callback route
]

onlineShop/urls.py
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

from taggit.managers import TaggableManager

from django.core.validators import MinValueValidator, MaxValueValidator


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.title}{ext}"
    return f"products/{instance.author}/{final_name}"


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField()


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to='media/', blank=True, default='man.png')
    email = models.EmailField(max_length=200, null=True)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=500, blank=True, null=True)
    ip_address = models.OneToOneField(IPAddress, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=20)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField()
    active = models.BooleanField()

    def __str__(self):
        return self.code


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_orderd = models.DateTimeField(auto_now_add=True)
    coplete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True, blank=True)
    coupons = models.ForeignKey(Coupon, on_delete=models.SET_NULL, blank=True, null=True)

    @property
    def get_total_products(self):
        orderItems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderItems])
        return total

    @property
    def get_total_price(self):
        orderItems = self.orderitem_set.all()
        total = sum([item.get_total_price for item in orderItems])
        return total


    @property
    def get_last_total_price(self):
        total = self.get_total_price
        if self.coupons:
            total -= self.coupons.discount

        if total < 0:
            total = 0
        return total


class Delivery(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField()
    active = models.BooleanField()



class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    address = models.TextField(max_length=500)
    city = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)


class Product(models.Model):
    STATUS_CHOICES = (
        ('published', 'Published'),
        ('draft', 'Draft'),
    )
    title = models.CharField(max_length=80)
    slug = models.CharField(max_length=100)
    price = models.FloatField()
    offPrice = models.FloatField(null=True, blank=True)
    description = models.TextField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    image = models.ImageField(null=True, blank=True)
    status = models.CharField(default='published', max_length=20, choices=STATUS_CHOICES)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    ratings = GenericRelation(Rating, related_query_name='products')
    hits = models.ManyToManyField(IPAddress, blank=True, related_name='hits')
    tags = TaggableManager()

    # published = ProductPublishManager()
    # objects = PostManager()

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        url = reverse('blog:product_detail', args=[self.id, self.slug])
        return url


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total_price(self):
        if self.product.offPrice:
            price = self.quantity * self.product.offPrice
        else:
            price = self.quantity * self.product.price
        return price

blog/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class AccountForm(forms.Form):
    first_name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100, required=False)
    email = forms.EmailField(max_length=100, required=False)
    phone = forms.CharField(max_length=12, required=False)
    address = forms.CharField(max_length=500, required=False)
    image = forms.FileField(required=False)

blog/views.py
from django.contrib import messages

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
import json

from django.urls import reverse_lazy

from .models import *

from .forms import CreateUserForm, AccountForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic import FormView
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth import logout

from django.db.models import Q

from django.db.models import Count


import random

from taggit.models import Tag

from django.contrib.auth.decorators import login_required






def homePage(request, tag_slug=None):
    products = Product.objects.filter(status='published')
    tag =None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = Product.objects.filter(tags__in=[tag])

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, coplete=False)

        order_items_count = order.get_total_products

    else:
        order_items_count = 0


    # Paginate Site With 6 Items Per A Page
    paginator = Paginator(products, 8)
    page = request.GET.get('page')

    # Post Of Certain Page
    try:
        products = paginator.page(page)

    # If Page Not Integer
    except PageNotAnInteger:
        products = paginator.page(1)

    # If Page NOt Exists
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {
        'products': products,
        'page': page,
        'order_items_count':  order_items_count,
    }
    return render(request, 'blog/partials/content.html', context)


def productDetail(request, pk, slug):
    product = get_object_or_404(Product, id=pk, slug=slug, status='published')

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, coplete=False)
        order_items_count = order.get_total_products

        user_ip = request.user.customer.ip_address
        if user_ip not in product.hits.all():
            product.hits.add(user_ip)
    else:
        order_items_count = 0

    product_tags = product.tags.values_list('id', flat=True)
    similar_products = Product.objects.filter(tags__in=product_tags, status='published').exclude(id=product.id)
    # print(similar_products)
    similar_products = similar_products.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    context = {
        'product': product,
        'similar_products': similar_products,
        'order_items_count': order_items_count,

    }
    return render(request, 'blog/partials/product_detail.html', context)
def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, coplete=False)
        items = OrderItem.objects.filter(order=order)
        delivery = Delivery.objects.filter(active=True)

        # Product Charges (static for now or can be dynamic)
        product_charges = 100  # Example static charge
        total_price = order.get_total_price  # No parentheses here as it's a property
        total_price_with_charges = total_price + product_charges

        # Default shipping fee (3000)
        shipping_fee = 3000

        if request.method == "POST":
            now = timezone.now()
            code = request.POST['code']
            
            # Coupon logic removed as requested

        order_items_count = order.get_total_products

        context = {
            'items': items,
            'order': order,
            'order_items_count': order_items_count,
            'delivery': delivery,
            'product_charges': product_charges,
            'total_price_with_charges': total_price_with_charges,  # Add this to pass the new total
            'shipping_fee': shipping_fee  # Pass the default shipping fee to the template
        }

        return render(request, 'blog/partials/cart.html', context)


# views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Order, OrderItem

def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, coplete=False)
        items = OrderItem.objects.filter(order=order)

        # Check if customer has filled in all necessary information
        if not (customer.first_name and customer.last_name and customer.address and customer.email and customer.phone):
            messages.error(request, 'Complete your personal information')
            return redirect('blog:cart')

    else:
        items = []
        order = {
            'get_total_price': 0,
            'get_total_products': 0,
        }
        return redirect('blog:login')

    # Adding shipping fee
    shipping_fee = 2  # Example shipping fee

    # Calculate total price including shipping fee
    total_price = order.get_total_price + shipping_fee
    
    if not order:
        # Handle case when order is not available
        return redirect('blog:cart')
    
    # Use order details and customer info for payment
    order_total = order.get_last_total_price
    customer_email = customer.email
    customer_phone = customer.phone
    customer_address = customer.address
    customer_name = f"{customer.first_name} {customer.last_name}"
    
    products_list = ', '.join([f"{item.product.title} x {item.quantity}" for item in items])
    
    
    
    context = {
        'items': items,
        'order': order,
        'customer': customer,
        'shipping_fee': shipping_fee,
        'total_price': total_price,
        'order_total': order_total,
        'customer_email': customer_email,
        'customer_name': customer_name,
        'products_list': products_list,
        'customer_phone': customer_phone,
        'customer_address': customer_address,
        'tx_ref': f"txref-{random.randint(100000, 999999)}",
    }

    return render(request, 'blog/partials/checkout.html', context)
print("items")


# @login_required
# def payment(request):
#     customer = request.user.customer
#     order, created = Order.objects.get_or_create(customer=customer, coplete=False)

    
    # if not order:
    #     # Handle case when order is not available
    #     return redirect('blog:cart')
    
    # # Use order details and customer info for payment
    # order_total = order.get_last_total_price
    # customer_email = customer.email
    # customer_phone = customer.phone
    # customer_address = customer.address
    # customer_name = f"{customer.first_name} {customer.last_name}"

#     context = {
        # 'order_total': order_total,
        # 'customer_email': customer_email,
        # 'customer_name': customer_name,
        # 'customer_phone': customer_phone,
        # 'customer_address': customer_address,
        # 'tx_ref': f"txref-{random.randint(100000, 999999)}",  # Generate a unique reference for the transaction
#     }
    
#     return render(request, 'blog/partials/payment.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=request.user.customer, coplete=False)
    orderItem, created = OrderItem.objects.get_or_create(product=product, order=order)


    if action == "add":
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == "remove":
        orderItem.quantity = (orderItem.quantity - 1)
    elif action == "delete":
        orderItem.delete()

    orderItem.save()
    if action == "delete":
        orderItem.delete()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('update item', safe=False)


class registerPage(FormView):
    template_name = 'blog/account/register.html'
    form_class = CreateUserForm
    success_url = reverse_lazy('blog:login')

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('blog:home')
        return super().get(*args, **kwargs)


    def form_valid(self, form):
        user = form.save()
        email = form.cleaned_data['email']
        customer = Customer.objects.create(user=user, email=email)
        return super().form_valid(form)


class loginPage(LoginView):
    template_name = 'blog/account/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('blog:home')

    def form_invalid(self, form):
        messages.error(self.request, 'Username or password is Incorrect')
        return super().form_invalid(self)


@login_required
def logoutPage(request):
    logout(request)
    return redirect('blog:login')


@login_required
def accountPage(request):
    customer = request.user.customer
    order_history = Order.objects.filter(customer=customer, coplete=True)
    if request.method == "POST":
        accForm = AccountForm(data=request.POST)
        if accForm.is_valid():
            accForm = AccountForm(data=request.POST)
            if accForm.is_valid():
                cd = accForm.cleaned_data
                customer.first_name = cd['first_name']
                customer.last_name = cd['last_name']
                customer.email = cd['email']
                customer.phone = cd['phone']
                customer.address = cd['address']
                image = request.FILES.get('image')
                if image:
                    customer.image = image
                customer.save()
                return redirect('blog:account')
    else:
        accForm = AccountForm()
    context = {
        'customer': customer,
        'accForm': accForm,

blog/templates/blog/account/login.html
{% extends 'blog/parents/base.html' %}

{% load static %}

{% block title %}Login{% endblock %}

{% block head %}{% endblock %}


{% block content %}
    <div class="container py-5 my-4">
        <div class="row">
            <div class="col-md-12 my-3">
                <div class="row">
                    <div class="col-md-4 offset-md-4">
                        <span class="anchor" id="formLogin"></span>

                        <!-- form card login with validation feedback -->
                        <div class="card card-outline-secondary">
                            <div class="card-header" style="background-color: #212529; color: white">
                                <h3 class="mb-0" style="float: left">Login</h3><br><br>
                            </div>
                            <div class="card-body">
                                <form class="form" role="form" autocomplete="off" id="loginForm" method="POST">
                                    {% if messages %}
                                        {% for message in messages %}

                                            <div class="alert alert-danger" role="alert">
                                                {{ message }}
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                    <div class="form-group">
                                        <label for="uname1">Username</label>
                                        <input type="text" class="form-control" name="username" id="uname1" required>
                                        <div class="invalid-feedback">Please enter your username or email</div>
                                    </div>
                                    <div class="form-group my-2">
                                        <label>Password</label>
                                        <input type="password" class="form-control" id="pwd1" name="password" required
                                               autocomplete="new-password">
                                        <div class="invalid-feedback">Please enter a password</div>
                                    </div>
                                <br>
                                    <a href="{% url 'blog:register' %}" class="small my-4" style="text-decoration: none">Do not have an account?</a>
                                    <button type="submit" class="btn btn-dark btn-lg my-4" id="btnLogin" style="float: right">
                                        Login
                                    </button>
                                    {% csrf_token %}
                                </form>
                            </div>
                            <!--/card-body-->
                        </div>
                        <!-- /form card login -->

                    </div>

                </div>
                <!--/row-->

            </div>
            <!--/col-->
        </div>
        <!--/row-->


    </div>
    <!--/container-->

{% endblock %}

blog/templates/blog/account/register.html
{% extends 'blog/parents/base.html' %}

{% block title %}Register{% endblock %}

{% block head %}{% endblock %}



{% block content %}
    <div class="container py-5">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-4 offset-md-4">
                        <span class="anchor" id="formLogin"></span>

                        <!-- form card login with validation feedback -->
                        <div class="card card-outline-secondary">
                            <div class="card-header" style="background-color: #212529; color: white">
                                <h3 class="mb-0" style="float: left">Register</h3><br><br>
                            </div>
                            <div class="card-body">
                                <form class="form" role="form" autocomplete="off" id="loginForm" method="POST">
                                    {% if form.errors %}
                                        {% for field in form %}
                                            {% if field.errors %}
                                                {% for err in field.errors %}
                                                    <div class="alert alert-danger" role="alert">
                                                        {{ field.label }}: {{ err }}
                                                    </div>
                                                {% endfor %}
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}

                                    <div class="form-group my-2">
                                        <label for="inputName">Username</label>
                                        <input name="username" type="text" class="form-control" id="inputName"
                                                required>
                                    </div>
                                    <div class="form-group my-2">
                                        <label for="inputEmail3">Email</label>
                                        <input name="email" type="email" class="form-control" id="inputEmail3"
                                                required>
                                    </div>
                                    <div class="form-group my-2">
                                        <label for="inputPassword3">Password</label>
                                        <input name="password1" type="password" class="form-control" id="inputPassword3"
                                                required>
                                    </div>
                                    <div class="form-group">
                                        <label for="inputVerify3">Confirm password</label>
                                        <input name="password2" type="password" class="form-control" id="inputVerify3"
                                                required>
                                    </div>
                                    <p class="my-2">Already have an account? <a href="{% url 'blog:login' %}">Login</a></p>
                                    <button type="submit" class="btn btn-dark btn-lg float-right" id="btnLogin" style="float: right">
                                        Register
                                    </button>
                                    {% csrf_token %}
                                </form>
                            </div>
                            <!--/card-body-->
                        </div>
                        <!-- /form card login -->

                    </div>

                </div>
                <!--/row-->

            </div>
            <!--/col-->
        </div>
        <!--/row-->


    </div>
    <!--/container-->
{% endblock %}